### ISSUE TITLE
Incorrect reading of page url from enum

### ISSUE THREAD

**Issue by aandrey1993** [SergheiBejenari/cucumberScenario#1]
Добрый день. Меня зовут Андрей. Я делал ревью Вашего тестового задания `cucumberScenario`.                 
В ходе ревью возникли некоторые вопросы. По каждому из них, я создам тикеты. Вы можете дать ответ, либо встречный вопрос, в комментариях по каждому тикету.

## Считывание URL страницы из enum.

Несмотря на то что был определен enum `Pages` для хранения информации о тестируемых страницах, URL для некоторых из них формируется заново, а для другой части сам Enum приводится к String и записывается в качестве URL. 

![изображение](https://user-images.githubusercontent.com/49781313/115870527-085f5c80-a448-11eb-8e16-f015c86a01e3.png)

![изображение](https://user-images.githubusercontent.com/49781313/115870679-3fce0900-a448-11eb-8cf2-039c35930f4d.png)

Как браузер должен открыть страницу `InternetBankingPage` если в качестве URL передается `"INTERNET_BANKING_PAGE"` ? Исправьте, пожалуйста, чтобы в конструкторах страниц из enum брался URL.

**Comment by SergheiBejenari** [comment]
Добрый день, я исправил все Ваши замечания и открыл Pull Request, данная проблема была устранена.
