### ISSUE TITLE
Incomprehensible logic of balance check

### ISSUE THREAD

**Issue by aandrey1993** [SergheiBejenari/cucumberScenario#3]
Не понятно как происходит проверка изначального баланса пользователей, так как сумма проверяется из статической переменной до получения реального баланса:

![изображение](https://user-images.githubusercontent.com/49781313/115872531-94728380-a44a-11eb-86b9-20f1b48286e3.png)

![изображение](https://user-images.githubusercontent.com/49781313/115872594-a6ecbd00-a44a-11eb-9cb4-67c854d831ba.png)

Подскажите, пожалуйста, какая логика заложена в проверки баланса и что тут проверяется ?

**Comment by SergheiBejenari** [comment]
Так как в задании было сказано составить cucumber scenario и обговорено о абстрактных классах, я писал все на скорую руку, дабы не тратить время. 
Это так же было исправлено.
