### ISSUE TITLE
Simplification of some parts of the code

### ISSUE THREAD

**Issue by aandrey1993** [SergheiBejenari/cucumberScenario#4]
Код для класса `Test`, по проверки баланса пользователя можно упростить. Данная проверка `UserCreator.USER_1_AMOUNT > 0` уже возвращает `boolean` значение, которое можно вернуть из метода.

![изображение](https://user-images.githubusercontent.com/49781313/115873483-a7d21e80-a44b-11eb-979b-98bd9f78e78a.png)

Ещё правильнее было оставить только 1 метод `isPositiveBill`, так как по сути `isPositiveBillUser1` и `isPositiveBillUser2` выполняет одно и тоже, только для разных значений. Данное значение можно передавать параметром в метод.

Исправьте, пожалуйста, данный момент.

**Comment by SergheiBejenari** [comment]
Я удалил данные методы и теперь amount записывается в ArrayList, достаются из него и сравниваются в assertEquals
