### ISSUE TITLE
Initial manipulation of the sum in the static class

### ISSUE THREAD

**Issue by aandrey1993** [SergheiBejenari/cucumberScenario#5]
Подскажите, пожалуйста, для чего делаются данные манипуляции с сумой в статическом классе ?

![изображение](https://user-images.githubusercontent.com/49781313/115874075-5fffc700-a44c-11eb-9f4c-ca1cf54e8963.png)

**Comment by SergheiBejenari** [comment]
Это так же было написано на скорую руку и было исправлено.
