### ISSUE TITLE
Transfer amount in cucumber script

### ISSUE THREAD

**Issue by aandrey1993** [SergheiBejenari/cucumberScenario#6]
В связи с чем был выбран подход для хранения суммы перевода в статическом классе, вместо того чтобы прописать её в сценарии cucumber? Например:

![изображение](https://user-images.githubusercontent.com/49781313/115874426-c1c03100-a44c-11eb-8d6b-1c687a0d0110.png)

После чего данную сумму можно получить в тесте, используя регулярное выражение:

![изображение](https://user-images.githubusercontent.com/49781313/115874524-dc92a580-a44c-11eb-89dd-52af2f8f179f.png)

**Comment by SergheiBejenari** [comment]
Я добавил в сценарий возможность изменять сумму перевода, но так как мне не известно какая сумма должна быть у пользователя до перевода, было решено взять ее из текущего баланса.
